branches:
  only:
    - master

services:
  - docker

jobs:
  include:
    - stage: centos6
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:centos6 --pull --rm --no-cache -f Dockerfile.centos6 .
        - docker push elnebuloso/sshd:centos6

    - stage: centos7
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:centos7 --pull --rm --no-cache -f Dockerfile.centos7 .
        - docker push elnebuloso/sshd:centos7

    - stage: debian8
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:debian8 --pull --rm --no-cache -f Dockerfile.debian8 .
        - docker push elnebuloso/sshd:debian8

    - stage: debian9
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:debian9 --pull --rm --no-cache -f Dockerfile.debian9 .
        - docker push elnebuloso/sshd:debian9

    - stage: ubuntu14
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:ubuntu14 --pull --rm --no-cache -f Dockerfile.ubuntu14 .
        - docker push elnebuloso/sshd:ubuntu14

    - stage: ubuntu16
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:ubuntu16 --pull --rm --no-cache -f Dockerfile.ubuntu16 .
        - docker push elnebuloso/sshd:ubuntu16

    - stage: ubuntu18
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --tag elnebuloso/sshd:ubuntu18 --pull --rm --no-cache -f Dockerfile.ubuntu18 .
        - docker push elnebuloso/sshd:ubuntu18