name: Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

jobs:
  main:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: centos6
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:centos6 --pull --rm --no-cache -f Dockerfile.centos6 .
          docker push elnebuloso/sshd:centos6
      - name: centos7
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:centos7 --pull --rm --no-cache -f Dockerfile.centos7 .
          docker push elnebuloso/sshd:centos7
      - name: debian8
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:debian8 --pull --rm --no-cache -f Dockerfile.debian8 .
          docker push elnebuloso/sshd:debian8
      - name: debian9
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:debian9 --pull --rm --no-cache -f Dockerfile.debian9 .
          docker push elnebuloso/sshd:debian9
      - name: debian10
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:debian10 --pull --rm --no-cache -f Dockerfile.debian10 .
          docker push elnebuloso/sshd:debian10
      - name: debian11
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:debian11 --pull --rm --no-cache -f Dockerfile.debian11 .
          docker push elnebuloso/sshd:debian11
      - name: ubuntu14
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:ubuntu14 --pull --rm --no-cache -f Dockerfile.ubuntu14 .
          docker push elnebuloso/sshd:ubuntu14
      - name: ubuntu16
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:ubuntu16 --pull --rm --no-cache -f Dockerfile.ubuntu16 .
          docker push elnebuloso/sshd:ubuntu16
      - name: ubuntu18
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:ubuntu18 --pull --rm --no-cache -f Dockerfile.ubuntu18 .
          docker push elnebuloso/sshd:ubuntu18
      - name: ubuntu19
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:ubuntu19 --pull --rm --no-cache -f Dockerfile.ubuntu19 .
          docker push elnebuloso/sshd:ubuntu19
      - name: ubuntu20
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:ubuntu20 --pull --rm --no-cache -f Dockerfile.ubuntu20 .
          docker push elnebuloso/sshd:ubuntu20
      - name: ubuntu22
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build --tag elnebuloso/sshd:ubuntu22 --pull --rm --no-cache -f Dockerfile.ubuntu22 .
          docker push elnebuloso/sshd:ubuntu22
